domain: "https://vaultwarden.homelab.sreafterhours.dev"

signupsVerify: true

replicas: 1

service:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

ingress:
  enabled: true
  hostname: vaultwarden.homelab.sreafterhours.dev
  nginxIngressAnnotations: true
  tlsSecret: homelab-cert

database:
  type: postgresql
  existingSecret: prod-db-creds
  existingSecretUserKey: pgusername
  existingSecretPasswordKey: pgpassword

storage:
  data:
    name: "vaultwarden-data"
    size: "10Gi"
    accessMode: "ReadWriteOnce"
    keepPvc: true
  attachments:
    name: "vaultwarden-files"
    size: "10Gi"
    accessMode: "ReadWriteOnce"
    keepPvc: true

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1 
