- hosts: postgres
  gather_facts: no
  become: true
  tasks:

    - name: Remove the default Postgres DNF modules
      ansible.builtin.command: dnf -qy module disable postgresql

    - name: Import the RPM key
      ansible.builtin.rpm_key:
        key: https://ftp.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL
        state: present

    - name: Install the repository
      ansible.builtin.dnf:
        name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
        state: present

    - name: Install PostgreSQL 17
      ansible.builtin.dnf:
        name: postgresql17-server
        state: present

    - name : Ensure the persistent data directory is existing
      ansible.builtin.file:
        path: "/data/postgresql"
        state: directory
        owner: "postgres"
        group: "postgres"
        mode: "0700"

    - name: Check packaged data directory
      ansible.builtin.stat:
        path: "{{ postgres_data }}"
      register: datadir

    - name : Delete the packaged data directory
      ansible.builtin.file:
        path: "{{ postgres_data }}"
        state: absent
      when: datadir.stat.isdir

    - name: Create symbolic link {{ postgres_data }}
      ansible.builtin.file:
        src: "/data/postgresql"
        dest: "{{ postgres_data }}"
        owner: "postgres"
        group: "postgres"
        state: link

    - name: Initialize the database
      ansible.builtin.command: /usr/pgsql-17/bin/postgresql-17-setup initdb
      args:
        creates: "{{ postgres_data }}/PG_VERSION"

    - name: Configure PostgreSQL
      ansible.builtin.template:
        src: postgresql.conf
        dest: "{{ postgres_data }}/postgresql.conf"
        mode: '0600'
        owner: postgres
        group: postgres
      notify: Restart PostgreSQL

    - name: Copy certificates and keys
      ansible.builtin.copy:
        src: "../common/files/{{ item.file }}"
        dest: "{{ postgres_data }}/{{ item.file }}"
        mode: "{{ item.perm }}"
        owner: postgres
        group: postgres
      no_log: true
      loop:
        - { file: "{{ domain }}.crt", perm: '0644' }
        - { file: "{{ domain }}.pem", perm: '0600' }
      notify: Restart PostgreSQL

    - name: Start and enable the service
      ansible.builtin.systemd:
        name: postgresql-17
        state: started
        enabled: yes

    - name: Enable firewall
      ansible.posix.firewalld:
        port: 5432/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - python3-psycopg2
          - postgresql17-contrib
        state: present

    ############### Configure the instance ###############

    ########## Postgres user ##########
    - name: Change postgres user's password
      community.postgresql.postgresql_user:
        name: postgres
        password: "{{ postgres_pass }}"
      become_user: postgres
    ########## Databases ##########
    - name: Create the SonarQube database
      community.postgresql.postgresql_db:
        name: "{{ sonarqube_db }}"
        comment: SonarQube database
      become_user: postgres
    ########## pg_hba.conf ##########
    - name: Allow connections from local subnet
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/17/data/pg_hba.conf
        contype: hostssl
        users: "postgres"
        source: "{{ my_ip }}"
        databases: "postgres,{{ sonarqube_db }}"
      become_user: postgres
      notify: Restart PostgreSQL
    - meta: flush_handlers

    ############### Roles ###############

    ########## SonarQube ##########
    - name : Create the SonarQube user
      community.postgresql.postgresql_user:
        name: "{{ sonarqube_user }}"
        password: "{{ sonarqube_pass }}"
      become_user: postgres
    - name: GRANT ALL PRIVILEGES ON DATABASE {{ sonarqube_db }} TO {{ sonarqube_user }}
      community.postgresql.postgresql_privs:
        login_db: postgres
        privs: "ALL"
        type: "database"
        obj: "{{ sonarqube_db }}"
        role: "{{ sonarqube_user }}"
      become_user: postgres
    - name: Allow connections for SonarQube user
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/17/data/pg_hba.conf
        contype: hostssl
        users: "{{ sonarqube_user }}"
        source: "{{ my_ip }}"
        databases: sonarqube
      become_user: postgres
      notify: Restart PostgreSQL

  vars:
    domain: sreafterhours.dev
    postgres_data: /var/lib/pgsql/17/data
    postgres_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64333632346432383932356565386161376331636539383535633532366633333761636261363864
      3965626338303332393935623466323531633065616562640a346434633635396266353963343030
      38373861666264663631386331346631643137663936626239333739336538663037613638393762
      3430323734663865660a666462646465326434623761353937343963376237313234643436626236
      3732
    sonarqube_db: "sonarqube"
    sonarqube_user: "sonarqube"
    sonarqube_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30323662666564326563663432613738666538376238303234333962633430656639653033393636
      3665666563646436323631366463316238353233363664360a336136386630353466333633636466
      66613166633037313236343365313736346166373135353161633531303533646365666539316435
      3936393539353530360a376463393666633962366565396531313538323335393431316138613830
      6266
    my_ip: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65653632303032396238393231663531633931666634363366336133633938323465343830316534
      3762346666383132616131326238353033623635656363330a396233623435323330636437653937
      32623832623264353764356130346631633535326663386365373536383532366536333433333437
      6637613037663064380a623839393366343562373666353337633862623764623332666332663430
      37336162373762333934303934666534326431353035336231353539376534316463

  handlers:

    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql-17
        state: restarted
