- hosts: jenkins
  gather_facts: no
  tasks:

    - name: Download the repo file
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'
      become: true

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
      become: true

    - name: Install prerequisites
      ansible.builtin.dnf:
        name:
          - fontconfig
          - java-21-openjdk
        state: latest
      become: true

    - name: Install Jenkins
      ansible.builtin.dnf:
        name: jenkins
        state: latest
      become: true

    - name: Start and enable Jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: true
      become: true
      when: not ansible_check_mode

    - name: Ensure Jenkins is running
      ansible.builtin.wait_for:
        port: 8080
        delay: 10
        timeout: 60
        state: started
      when: not ansible_check_mode

    - name: Get the initial admin password
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      become: true

    - name: Print the initial admin password
      ansible.builtin.debug:
        msg: "Initial admin password: {{ jenkins_password['content'] | b64decode }}"

    - name: Enable the firewall for Jenkins HTTPs
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        immediate: true
        state: enabled
      become: true
