- hosts: nginx
  gather_facts: yes
  become: true
  tasks:
    
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Configure Nginx
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: Restart Nginx

    - name: Copy certificates and keys
      ansible.builtin.copy:
        src: "../common/files/{{ item.file }}"
        dest: "/etc/nginx/{{ item.file }}"
        mode: "{{ item.perm }}"
      no_log: true
      loop:
        - { file: "{{ domain }}.crt", perm: '0644' }
        - { file: "{{ domain }}.pem", perm: '0600' }
      notify: Restart Nginx

    - name: Configure virtual hosts
      ansible.builtin.template:
        src: "{{ item }}.conf"
        dest: "/etc/nginx/conf.d/{{ item }}.conf"
        mode: '0644'
      with_items:
        - prometheus
        - sonarqube
      notify: Restart Nginx

    - name : Set SELinux boolean httpd_can_network_connect
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
      notify: Restart Nginx
      when: ansible_os_family == "RedHat"

    - name: Ensure Nginx is started and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
      when: not ansible_check_mode

  vars:
    domain: sreafterhours.dev
  
  handlers:

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
