---
- hosts: prometheus
  become: true
  tasks:
    - name: Hack | Create the user
      ansible.builtin.user:
        name: "prometheus"
        system: true
        shell: "/usr/sbin/nologin"
        home: "/etc/prometheus"
        create_home: true
    - name: Hack | Copy the certificate and key file
      ansible.builtin.copy:
        src: "/data/Google-Cloud/homelab.sreafterhours.dev.{{ item }}"
        dest: "/etc/prometheus"
        owner: "prometheus"
        group: "prometheus"
        mode: 0600
      with_items:
        - "pem"
        - "crt"
    - name: Install and configure Prometheus
      ansible.builtin.include_role:
        name: prometheus.prometheus.prometheus
      vars:
        prometheus_version: "3.4.2"
        # prometheus_config_flags:
        #   - "--web.enable-lifecycle"
        prometheus_targets:
          node:
            - targets:
                - "localhost:9100"
              labels:
                job: node_exporter
        prometheus_web_config:
          tls_server_config:
            cert_file: /etc/prometheus/homelab.sreafterhours.dev.crt
            key_file: /etc/prometheus/homelab.sreafterhours.dev.pem
          http_server_config: {}
          basic_auth_users: {}
