---
- hosts: nodes
  pre_tasks:
    - name: Hack | Create the user
      ansible.builtin.user:
        name: "node-exp"
        system: true
        shell: "/usr/sbin/nologin"
        home: "/etc/node_exporter"
        create_home: false
      become: true
      when: ansible_os_family == "RedHat" or ansible_os_family =="Debian"
    - name: Hack | Create the directory
      ansible.builtin.file:
        path: "/etc/node_exporter"
        state: directory
        owner: "node-exp"
        group: "node-exp"
        mode: 0755
      become: true
      when: ansible_os_family == "RedHat" or ansible_os_family =="Debian"
    - name: Hack | Copy the certificate and key file (Linux)
      ansible.builtin.copy:
        src: "/data/Projects/homelab/local/homelab.sreafterhours.dev.{{ item }}"
        dest: "/etc/node_exporter"
        owner: "node-exp"
        group: "node-exp"
        mode: 0600
      with_items:
        - "pem"
        - "crt"
      become: true
      when: ansible_os_family == "RedHat" or ansible_os_family =="Debian"
    - name: Hack | Copy the certificate and key file (Windows)
      ansible.builtin.copy:
        src: "/data/Projects/homelab/local/homelab.sreafterhours.dev.{{ item }}"
        dest: 'C:\Program Files\windows_exporter'
        mode: 0600
      with_items:
        - "pem"
        - "crt"
      when: ansible_os_family == "Windows"
  tasks:
    - name: Install and configure node exporters (Linux)
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
      vars:
        node_exporter_version: "1.9.1"
        node_exporter_tls_server_config:
          cert_file: /etc/node_exporter/homelab.sreafterhours.dev.crt
          key_file: /etc/node_exporter/homelab.sreafterhours.dev.pem
      when: ansible_os_family == "RedHat" or ansible_os_family =="Debian"
    - name: Install and configure node exporters (Windows)
      ansible.builtin.include_role:
        name: antmelekhin.windows_exporter
      vars:
        windows_exporter_version: '0.31.2'
        windows_exporter_tls_server_config:
          cert_file: 'C:\Program Files\windows_exporter\homelab.sreafterhours.dev.crt'
          key_file: 'C:\Program Files\windows_exporter\homelab.sreafterhours.dev.pem'
      when: ansible_os_family == "Windows"
  post_tasks:
    - name: Enable firewall access to node exporter
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        immediate: true
        state: enabled
      become: true
      when: ansible_os_family == "RedHat"
