---
- hosts: prometheus
  become: true
  pre_tasks:
    - name: Create the user
      ansible.builtin.user:
        name: "prometheus"
        system: true
        shell: "/usr/sbin/nologin"
        home: "/etc/prometheus"
        create_home: true
    - name: Copy the certificate and key file
      ansible.builtin.copy:
        src: "../common/files/{{ item.file }}"
        dest: "/etc/prometheus/{{ item.file }}"
        owner: "prometheus"
        group: "prometheus"
        mode: "{{ item.perm }}"
      no_log: true
      loop:
        - { file: "{{ domain }}.crt", perm: '0644' }
        - { file: "{{ domain }}.pem", perm: '0600' }
  tasks:
    - name: Install and configure Prometheus
      ansible.builtin.include_role:
        name: prometheus.prometheus.prometheus
      vars:
        prometheus_version: "3.4.2"
        prometheus_global:
          scrape_interval: 1s
        prometheus_scrape_configs:
          - job_name: "prometheus"
            scheme: https
            metrics_path: "{{ prometheus_metrics_path }}"
            static_configs:
              - targets:
                  - "node1.{{ domain }}:9090"
          - job_name: "node"
            scheme: https
            file_sd_configs:
              - files:
                  - "{{ prometheus_config_dir }}/file_sd/node.yml"
          # - job_name: "applications"
          #   file_sd_configs:
          #     - files:
          #         - "{{ prometheus_config_dir }}/file_sd/applications.yml"
        prometheus_targets:
          node:
            - targets:
                - "node1.{{ domain }}:9100"
              labels:
                job: node_exporter
          # applications:
          #   - targets:
          #       - "node1.{{ domain }}:8081"
          #     labels:
          #       environment: development
        prometheus_web_config:
          tls_server_config:
            cert_file: /etc/prometheus/{{ domain }}.crt
            key_file: /etc/prometheus/{{ domain }}.pem
          http_server_config: {}
          basic_auth_users: {}
  vars:
    domain: sreafterhours.dev
