- hosts: all
  gather_facts: true
  tasks:

    - name: Install tools
      ansible.builtin.dnf:
        name:
          - policycoreutils-python-utils
          - vim
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    # - name: Set SELinux to permissive
    #   ansible.posix.selinux:
    #     policy: targeted
    #     state: permissive
    #   become: true
    #   when: ansible_os_family == "RedHat"
    #   notify: Reboot host

  handlers:
    - name: Reboot host
      become: true
      reboot: