- hosts: all
  gather_facts: true
  tasks:

    - name: Install tools (RedHat)
      ansible.builtin.dnf:
        name:
          - policycoreutils-python-utils
          - vim
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install tools (Ubuntu)
      ansible.builtin.apt:
        name:
          - vim
          - unzip
        state: present
      become: true
      when: ansible_os_family == "Debian"

  handlers:
    - name: Reboot host
      become: true
      reboot: